semantic_segmentation_server:
  color_topic : /camera/color/image_raw
  model:
    model_path: $(find semantic_segmentation_ros)/assets/model/deeplabv3plus_637_mIOU=0.9096.pt
    encoder_name : "resnet34"
    encoder_weights : "imagenet"
    in_channels : 3
    classes : 5
  