semantic_segmentation_server:
  camera:
    color_topic : /camera/color/image_raw
  model:
    model_name : "deeplabv3plus"
    encoder_name : "resnet34"
    encoder_weights : "imagenet"
    in_channels : 3
    classes : 5
    model_path: $(find semantic_segmentation_ros)/assets/model/deeplabv3plus_86_mIOU=0.9067.pt
  